// megafunction wizard: %ROM: 1-PORT%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altsyncram 

// ============================================================
// File Name: Boxtheta_Rom.v
// Megafunction Name(s):
// 			altsyncram
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 18.1.0 Build 625 09/12/2018 SJ Lite Edition
// ************************************************************


//Copyright (C) 2018  Intel Corporation. All rights reserved.
//Your use of Intel Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Intel Program License 
//Subscription Agreement, the Intel Quartus Prime License Agreement,
//the Intel FPGA IP License Agreement, or other applicable license
//agreement, including, without limitation, that your use is for
//the sole purpose of programming logic devices manufactured by
//Intel and sold by Intel or its authorized distributors.  Please
//refer to the applicable agreement for further details.


//altsyncram ADDRESS_ACLR_A="NONE" CLOCK_ENABLE_INPUT_A="BYPASS" CLOCK_ENABLE_OUTPUT_A="BYPASS" DEVICE_FAMILY="Cyclone IV E" ENABLE_RUNTIME_MOD="NO" INIT_FILE="../ip/Boxtheta_Rom/Boxtheta_rom.mif" NUMWORDS_A=4096 OPERATION_MODE="ROM" OUTDATA_ACLR_A="NONE" OUTDATA_REG_A="UNREGISTERED" WIDTH_A=12 WIDTH_BYTEENA_A=1 WIDTHAD_A=12 address_a clock0 q_a
//VERSION_BEGIN 18.1 cbx_altera_syncram_nd_impl 2018:09:12:13:04:24:SJ cbx_altsyncram 2018:09:12:13:04:24:SJ cbx_cycloneii 2018:09:12:13:04:24:SJ cbx_lpm_add_sub 2018:09:12:13:04:24:SJ cbx_lpm_compare 2018:09:12:13:04:24:SJ cbx_lpm_decode 2018:09:12:13:04:24:SJ cbx_lpm_mux 2018:09:12:13:04:24:SJ cbx_mgl 2018:09:12:13:10:36:SJ cbx_nadder 2018:09:12:13:04:24:SJ cbx_stratix 2018:09:12:13:04:24:SJ cbx_stratixii 2018:09:12:13:04:24:SJ cbx_stratixiii 2018:09:12:13:04:24:SJ cbx_stratixv 2018:09:12:13:04:24:SJ cbx_util_mgl 2018:09:12:13:04:24:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = M9K 6 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"OPTIMIZE_POWER_DURING_SYNTHESIS=NORMAL_COMPILATION"} *)
module  Boxtheta_Rom_altsyncram
	( 
	address_a,
	clock0,
	q_a) /* synthesis synthesis_clearbox=1 */;
	input   [11:0]  address_a;
	input   clock0;
	output   [11:0]  q_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   clock0;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]   wire_ram_block1a_0portadataout;
	wire  [0:0]   wire_ram_block1a_1portadataout;
	wire  [0:0]   wire_ram_block1a_2portadataout;
	wire  [0:0]   wire_ram_block1a_3portadataout;
	wire  [0:0]   wire_ram_block1a_4portadataout;
	wire  [0:0]   wire_ram_block1a_5portadataout;
	wire  [0:0]   wire_ram_block1a_6portadataout;
	wire  [0:0]   wire_ram_block1a_7portadataout;
	wire  [0:0]   wire_ram_block1a_8portadataout;
	wire  [0:0]   wire_ram_block1a_9portadataout;
	wire  [0:0]   wire_ram_block1a_10portadataout;
	wire  [0:0]   wire_ram_block1a_11portadataout;
	wire  [11:0]  address_a_wire;

	cycloneive_ram_block   ram_block1a_0
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_0portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_0.clk0_core_clock_enable = "none",
		ram_block1a_0.clk0_input_clock_enable = "none",
		ram_block1a_0.connectivity_checking = "OFF",
		ram_block1a_0.init_file = "../ip/Boxtheta_Rom/Boxtheta_rom.mif",
		ram_block1a_0.init_file_layout = "port_a",
		ram_block1a_0.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_0.mem_init0 = 2048'hF18C64DA556E06CEC387399925548E510F83C71CCDB553FBFF00FC1E3CE6DA90FC00007FF80F87190007FFFC01FC1E72E01FC0F0F199B54FFC1E1C739B696CE51E3CE3324B5260DEC73999B6AAB3FD7B6333369556C715EE33324A55247C533C99B695569C0EB3766DB5AA9670326612B4B555B7006A2582D2B56B63FE54144A6AD6A4C7E358288AAD529B8F8D4FA4F2555A4C7F12C0A3E8AB5263FF24814223AAD338076B0287DB54931FF344F2FBC4ADB38019571A67E75B33C1E593CA0845B663FF12903414B84CC7FC68B069C784B30FF8D560D66F846E3FF1AAC0D398B198FFF34D80D8666EE78072567ECCD0BB380072AB875DDF42C7FE32ACF9588F42,
		ram_block1a_0.mem_init1 = 2048'h1F328A70EDB0000003CD2D3FC8980000F072548FCA9C0000FF8DAAC7C9BE000000F34B67CD3100001E0CD567C5408000FFF1B527F69F400080076D27FB20C0003FFC4B2E0CDFA000E001CB6CF36650001E079B59DCA0500061FF1956311050009C1C1965C3506600638019AA7E532F0098E01CD59E57D24066780E6AC62838A0931C0735673368B06D8E01C927D9E84896CE0032A7F4E3B84B663FC4AC0CF444AD26783DA9F98E5855A663F1B6797A34AAB4CE01953C9ADC2A9499F3CA9F4D1C5555A63FE698DF10A555699F79B7D271695556CE0329C917DA52A96C7F34FBDF36DA95ACC71A82ED64DB5AAD31E260898CD9254949E72FA439CC9B5AAD9FCB3B,
		ram_block1a_0.operation_mode = "rom",
		ram_block1a_0.port_a_address_clear = "none",
		ram_block1a_0.port_a_address_width = 12,
		ram_block1a_0.port_a_data_out_clear = "none",
		ram_block1a_0.port_a_data_out_clock = "none",
		ram_block1a_0.port_a_data_width = 1,
		ram_block1a_0.port_a_first_address = 0,
		ram_block1a_0.port_a_first_bit_number = 0,
		ram_block1a_0.port_a_last_address = 4095,
		ram_block1a_0.port_a_logical_ram_depth = 4096,
		ram_block1a_0.port_a_logical_ram_width = 12,
		ram_block1a_0.ram_block_type = "AUTO",
		ram_block1a_0.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_1
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_1portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_1.clk0_core_clock_enable = "none",
		ram_block1a_1.clk0_input_clock_enable = "none",
		ram_block1a_1.connectivity_checking = "OFF",
		ram_block1a_1.init_file = "../ip/Boxtheta_Rom/Boxtheta_rom.mif",
		ram_block1a_1.init_file_layout = "port_a",
		ram_block1a_1.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_1.mem_init0 = 2048'h01F078E399B4ADCCFC07C1E1C666D5310FFC07E0F1C665570000FFE03F071CDAFFFFFF80000FF81E00000003FFFC01F11FFFC00FF0787325FC01FC0F8718DA4901FC1F0E38C92A9E3F07878E66695679E0F0F18CCDADA61B0F0E39CC92D69CE878718CCDB554C0D9E38C664D2AA47EA18C73336D554C233F318CD92954980D78E6326DAD4A601AFB9CC9B6A5298F910B3336DAD5A4FF95E366C92955B700D41499B69555B3FE543332494AA598F1AC286496AAAD9806C828C96955491C39502892D6AA5B1FF2A79025AD56B33FE49857695AAD667FCD4FA8DA955ACCFFC92066B5AAA591FFCAB9D7AD555B6781DA9F936AAAA4CC00CA9F2B52AB5B30F8CACF2B,
		ram_block1a_1.mem_init1 = 2048'h4A96460F0ED0000056A49CFFF1280000552933800CD40000555B663FF12A0000AA56D8E00E5B0000AAA5B31FF9958000AAAB6CE0072AC000D552DB1FFC4A4000555526E1F09560004AAB591C03B53000AB52B6C7DF353000B5554B31FE253000D6AAB4DC3C6520004AD54B66006560002D4AB5B380654F80B4AD5AD9C03298C0DA56AD6CE03A2720492B54A4E01D58602494AA966006AFD4924B555263F15392C9B4AD6B67FED99766CB4AAB6E01A9DC332694AB4CFF29EBCCD92D5959806B146666CB555278EAE43999B2D5D48FE5048E666494A967F285E39CCDB6AA93FD4238E319369549835E871C63365AA91F26F0E1C6726D4D60333E0F1C6336D558CE,
		ram_block1a_1.operation_mode = "rom",
		ram_block1a_1.port_a_address_clear = "none",
		ram_block1a_1.port_a_address_width = 12,
		ram_block1a_1.port_a_data_out_clear = "none",
		ram_block1a_1.port_a_data_out_clock = "none",
		ram_block1a_1.port_a_data_width = 1,
		ram_block1a_1.port_a_first_address = 0,
		ram_block1a_1.port_a_first_bit_number = 1,
		ram_block1a_1.port_a_last_address = 4095,
		ram_block1a_1.port_a_logical_ram_depth = 4096,
		ram_block1a_1.port_a_logical_ram_width = 12,
		ram_block1a_1.ram_block_type = "AUTO",
		ram_block1a_1.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_2
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_2portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_2.clk0_core_clock_enable = "none",
		ram_block1a_2.clk0_input_clock_enable = "none",
		ram_block1a_2.connectivity_checking = "OFF",
		ram_block1a_2.init_file = "../ip/Boxtheta_Rom/Boxtheta_rom.mif",
		ram_block1a_2.init_file_layout = "port_a",
		ram_block1a_2.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_2.mem_init0 = 2048'h01FF80FC1E38C965FFF801FE078719A4F00007FF01F8799A0000FFFFC007E0E3FFFFFFFFFFF0001FFFFFFFFFFFFC000F00003FFFF007F0E3FC0003FF80F839DBFFFC00FE07C719B400FF807E1E18CD2DE00FF07C3C636D53FF01F83C71CDB54F07F07C3C73325560E07C1E3CE66D2B3F7C0F0F1CCCDA8A3E0F83C718CDB55679E1F1E39CD92AACF97C38719C9B5AD9F90F0E39CC92552619E1C718CC92AA980D78718CCC96AB67F60E38C66CB5A5301AE38E6664B5548FE538E73324B552601A8E319936B55B3875E39CCD9695491FCD18C664D2D5698F9AC673365A556DC0127399934B556CC0329CCCC92D556CE076E6666DA5556CE0E631993695AD6CF0E6,
		ram_block1a_2.mem_init1 = 2048'h932494AAA5BFFFFF64C92955549FFFFF99B25AD55A4FFFFF666DB4AAAB67FFFFCC9B6D4AA537FFFF3336DA5554B3FFFFCCCDB6B55299FFFF199B6DAAAAD9DFFF66664B4AAA4CEFFF8CCD9256A96CF7FF339B2495756CF3FFC6666DA5556CF1FF18CCD969552CE0FF7319924B552CE07FCE7326DAD52CC03F38CE6C929569871FE398C9B6B5691FCF8E339936B54B387738E73324B552601BE38C6664B554CFE50E38CE4DB555B81A78F38CCDB4AB67E6C3C718CD96AA980D0F1E319D92D527197878F3999B5259F9C1E1C319992AACF90F878718CDB55679FC1F0E38CCDAAB3CC0FC1E38E66D293F07E07C3863325560FF01F87C7189B56FC00FE07C38E66D59,
		ram_block1a_2.operation_mode = "rom",
		ram_block1a_2.port_a_address_clear = "none",
		ram_block1a_2.port_a_address_width = 12,
		ram_block1a_2.port_a_data_out_clear = "none",
		ram_block1a_2.port_a_data_out_clock = "none",
		ram_block1a_2.port_a_data_width = 1,
		ram_block1a_2.port_a_first_address = 0,
		ram_block1a_2.port_a_first_bit_number = 2,
		ram_block1a_2.port_a_last_address = 4095,
		ram_block1a_2.port_a_logical_ram_depth = 4096,
		ram_block1a_2.port_a_logical_ram_width = 12,
		ram_block1a_2.ram_block_type = "AUTO",
		ram_block1a_2.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_3
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_3portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_3.clk0_core_clock_enable = "none",
		ram_block1a_3.clk0_input_clock_enable = "none",
		ram_block1a_3.connectivity_checking = "OFF",
		ram_block1a_3.init_file = "../ip/Boxtheta_Rom/Boxtheta_rom.mif",
		ram_block1a_3.init_file_layout = "port_a",
		ram_block1a_3.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_3.mem_init0 = 2048'hFE0000FFE03F0E76FFFFFE0007F81E39000007FFFE007E1CFFFF00000007FF03FFFFFFFFFFFFFFE0000000000003FFFFFFFFFFFFF0000FE0FC0000007FF807C70003FFFE003F078DFFFF8001FE07C31BE0000FFC03E0E33600FFF803F03C7325FFF003FC0F0E332AE003FE03E1E3196A03FF00FC3C39996BFF803F07C38CCD2DE00FE07C38E665AD03F80F838739B4ADFF01F83C71CC92ADE03F07C38E664AA907F07C3C71992D5BFE07C1E38C6C9553E07E1E1C73325AB607E0F0E38CC92AAC7E0F870E73369559E07C3C718CDB4A9607C1E3CE3324A52C3E0F0E39CCDB555BF07870C73325AAA483C3C71CCCDA555B1E1E1C633325AAB4F078F18C64DA554B,
		ram_block1a_3.mem_init1 = 2048'hE3C718CCC920000078F1CE6666D000001E3C631993680000878E38CCCDB40000F0E38E73365A00003C38E399992500000F0E38C664D28000E1E38E33336D60007878738CCC96B0000F0E1C6732495800C3E3C71999B6A400F87871C666495A001F0F1E7199B6B50083E1E38C66494A80F07C38E319B695403F0F8F1CE64D2AA003E0F1C739B25550F03C1E38C66DAD283F07C3C7399B4AB403F07878C6669552F03F0F8E39992D497F03F0F1C7324AAD03F81F0E18CCD2A4F01FC1E1E319B5B47F80FC1E1C636D5401FE03E1E1CCC954F007F81F0E399B54FFE00FC0F0E3325500FFE03F078E3255F8007FC07C3C664AFFFE007F81F1C64A000FFF803F078E6D,
		ram_block1a_3.operation_mode = "rom",
		ram_block1a_3.port_a_address_clear = "none",
		ram_block1a_3.port_a_address_width = 12,
		ram_block1a_3.port_a_data_out_clear = "none",
		ram_block1a_3.port_a_data_out_clock = "none",
		ram_block1a_3.port_a_data_width = 1,
		ram_block1a_3.port_a_first_address = 0,
		ram_block1a_3.port_a_first_bit_number = 3,
		ram_block1a_3.port_a_last_address = 4095,
		ram_block1a_3.port_a_logical_ram_depth = 4096,
		ram_block1a_3.port_a_logical_ram_width = 12,
		ram_block1a_3.ram_block_type = "AUTO",
		ram_block1a_3.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_4
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_4portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_4.clk0_core_clock_enable = "none",
		ram_block1a_4.clk0_input_clock_enable = "none",
		ram_block1a_4.connectivity_checking = "OFF",
		ram_block1a_4.init_file = "../ip/Boxtheta_Rom/Boxtheta_rom.mif",
		ram_block1a_4.init_file_layout = "port_a",
		ram_block1a_4.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_4.mem_init0 = 2048'h000000FFFFC00F870000000007FFE03EFFFFF80000007FE0FFFFFFFFFFF80003FFFFFFFFFFFFFFFF0000000000000000000000000FFFFFE003FFFFFFFFF8003FFFFFFFFE0000FF83FFFF800001FFC0F8E0000003FFE01F0E000007FFF003F0E3000FFFFC00FE0F191FFFFE001FE0F8E6FFFF0003FC078719FF8000FFC07C3CE4E0001FFC07E1E39B0007FF807F078C6400FFF803F03C719B1FFF003F81E1C664FFF003FC0F871CC9FE003FE07C1C7336E001FE03F0F1C66D001FF01F83C7199A01FF80FE0F0E73341FFC03F07C38C64DFFC01FC1F0E39C9AFE00FE07C3C73336F007F03F0F1C666D803FC0FC3C39CCC901FE03E0F0E399920FF80F83E3C63326,
		ram_block1a_4.mem_init1 = 2048'h03F81F0F0E3FFFFF80FE0F87871FFFFFE03F83E1E38FFFFFF80FC0F0F1C7FFFFFF03F07C3863FFFF3FC0FC1E1E39FFFF0FF03F07871CFFFF01FC0FC3C38E7FFF807F83F0F0E73FFFF00FE0783C719FFFFC03F81E1E38C7FFFF807E07878E63FF1FF01F81E1C739FF03FE03F078718CFF007FC0FC1E38E67FC00FF01F078E333FFC00FE07C1C3999FFFC01FC0F871CE4F3FF803F83E1C732703FF807F0787199B003FF00FC1E1CE6D8003FF01F83C7336FC001FF01F0F1CC9FFE001FE03E1C6267FFF001FE07C719901FFFC01FE0F0E660007FFE00FC1E39900000FFF00FC3C66FF00003FF80FC399FFFF80007FC07873FFFFFF8001FE078C000FFFFFC007F071,
		ram_block1a_4.operation_mode = "rom",
		ram_block1a_4.port_a_address_clear = "none",
		ram_block1a_4.port_a_address_width = 12,
		ram_block1a_4.port_a_data_out_clear = "none",
		ram_block1a_4.port_a_data_out_clock = "none",
		ram_block1a_4.port_a_data_width = 1,
		ram_block1a_4.port_a_first_address = 0,
		ram_block1a_4.port_a_first_bit_number = 4,
		ram_block1a_4.port_a_last_address = 4095,
		ram_block1a_4.port_a_logical_ram_depth = 4096,
		ram_block1a_4.port_a_logical_ram_width = 12,
		ram_block1a_4.ram_block_type = "AUTO",
		ram_block1a_4.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_5
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_5portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_5.clk0_core_clock_enable = "none",
		ram_block1a_5.clk0_input_clock_enable = "none",
		ram_block1a_5.connectivity_checking = "OFF",
		ram_block1a_5.init_file = "../ip/Boxtheta_Rom/Boxtheta_rom.mif",
		ram_block1a_5.init_file_layout = "port_a",
		ram_block1a_5.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_5.mem_init0 = 2048'hFFFFFF0000000FF8FFFFFFFFF800003FFFFFFFFFFFFF8000FFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFF0000000000000000000000000000001F000000000007FFFF00000001FFFFFF8000007FFFFFFFC0071FFFFFFFFFE000FEFFFFFFFFF0000FE0FFFFFFFC0001FF07FFFFFE00001FF81EFFFF000003FF80F8FF8000003FFC03E3E0000003FFE01F870000007FFF007C1C000007FFF003F0780000FFFF801FC1E3000FFFFC007F03C701FFFFE003FC0F0E1FFFFE000FF03E1CFFFFF0007FC0F879FFFF8001FF01F0F3FFFC000FFC07C1C3FFC0003FF01F8386FE0001FFC03F0F0EF0000FFF00FC1E1C80003FFC03F83C380001FFE00FE078710007FF801FC1F0E1,
		ram_block1a_5.mem_init1 = 2048'h03FFE00FF03FFFFF00FFF007F81FFFFF003FFC01FC0FFFFF000FFF00FE07FFFF0003FF803F83FFFFC000FFE01FC1FFFFF0003FF807E0FFFFFE000FFC03F07FFFFF8003FF00F83FFFFFF0007FC07E1FFFFFFC001FE03F07FFFFFF8007F80F83FF1FFFE001FE07C1FF03FFFC007F81F0FF007FFF001FC0F87F000FFFE007F03C3F0000FFF801FC1E1F00001FFF007E0F8FC00003FFC01F83C7FC00007FF807E1E3FFC0000FFE01F071FFFC0001FFC07C38FFFFE0001FF01F0EFFFFFE0003FE07C77FFFFFE0007F81E101FFFFFE000FF0780007FFFFF001FC1E00000FFFFF003F870000003FFFF003E1000000007FFF807C0000000001FFF80FFFF000000007FF81,
		ram_block1a_5.operation_mode = "rom",
		ram_block1a_5.port_a_address_clear = "none",
		ram_block1a_5.port_a_address_width = 12,
		ram_block1a_5.port_a_data_out_clear = "none",
		ram_block1a_5.port_a_data_out_clock = "none",
		ram_block1a_5.port_a_data_width = 1,
		ram_block1a_5.port_a_first_address = 0,
		ram_block1a_5.port_a_first_bit_number = 5,
		ram_block1a_5.port_a_last_address = 4095,
		ram_block1a_5.port_a_logical_ram_depth = 4096,
		ram_block1a_5.port_a_logical_ram_width = 12,
		ram_block1a_5.ram_block_type = "AUTO",
		ram_block1a_5.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_6
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_6portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_6.clk0_core_clock_enable = "none",
		ram_block1a_6.clk0_input_clock_enable = "none",
		ram_block1a_6.connectivity_checking = "OFF",
		ram_block1a_6.init_file = "../ip/Boxtheta_Rom/Boxtheta_rom.mif",
		ram_block1a_6.init_file_layout = "port_a",
		ram_block1a_6.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_6.mem_init0 = 2048'h0000000000000FFF000000000000003F000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF80FFFFFFFFFFFFC000FFFFFFFFFFE00001FFFFFFFFF000001FFFFFFFFC000000FFFFFFFE00000007FEFFFF000000007FF8FF8000000003FFE0E0000000001FFF800000000000FFFC03000000000FFFF007000000007FFFC01F00000003FFFF003F0000001FFFFC00FE000001FFFFF001FC00000FFFFFC007F800007FFFFF000FF00003FFFFFC003FC0003FFFFFF0007F8101FFFFFFC000FF010FFFFFFF0003FE037FFFFFFC0007FC07FFFFFFE0001FF80FFFFFFF80003FF01F,
		ram_block1a_6.mem_init1 = 2048'h03FFFFF0003FFFFF00FFFFF8001FFFFF003FFFFE000FFFFF000FFFFF0007FFFF0003FFFFC003FFFF0000FFFFE001FFFF00003FFFF800FFFF00000FFFFC007FFF000003FFFF003FFF0000007FFF801FFF0000001FFFC007FF00000007FFF003FFE0000001FFF801FFFC0000007FFE00FFFF8000001FFF007FFFF0000007FFC03FFFFF000001FFE01FFFFFE000007FF00FFFFFFC00001FFC07FFFFFF800007FE03FFFFFFF00001FF81FFFFFFFE00007FC0FFFFFFFFE0001FF0FFFFFFFFFC0007F87FFFFFFFFF8001FE01FFFFFFFFF0007F0007FFFFFFFE001F00000FFFFFFFC0070000003FFFFFFC01000000007FFFFF800000000001FFFFF0000000000007FFFE,
		ram_block1a_6.operation_mode = "rom",
		ram_block1a_6.port_a_address_clear = "none",
		ram_block1a_6.port_a_address_width = 12,
		ram_block1a_6.port_a_data_out_clear = "none",
		ram_block1a_6.port_a_data_out_clock = "none",
		ram_block1a_6.port_a_data_width = 1,
		ram_block1a_6.port_a_first_address = 0,
		ram_block1a_6.port_a_first_bit_number = 6,
		ram_block1a_6.port_a_last_address = 4095,
		ram_block1a_6.port_a_logical_ram_depth = 4096,
		ram_block1a_6.port_a_logical_ram_width = 12,
		ram_block1a_6.ram_block_type = "AUTO",
		ram_block1a_6.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_7
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_7portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_7.clk0_core_clock_enable = "none",
		ram_block1a_7.clk0_input_clock_enable = "none",
		ram_block1a_7.connectivity_checking = "OFF",
		ram_block1a_7.init_file = "../ip/Boxtheta_Rom/Boxtheta_rom.mif",
		ram_block1a_7.init_file_layout = "port_a",
		ram_block1a_7.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_7.mem_init0 = 2048'h0000000000000FFF000000000000003F000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007F0000000000003FFF00000000001FFFFF000000000FFFFFFF00000003FFFFFFFF000001FFFFFFFFFE0000FFFFFFFFFFF8007FFFFFFFFFFFE01FFFFFFFFFFFFF80FFFFFFFFFFFFFC00FFFFFFFFFFFFF000FFFFFFFFFFFFC000FFFFFFFFFFFF0000FFFFFFFFFFFC0001FFFFFFFFFFF00003FFFFFFFFFFC00007FFFFFFFFFF00000FFFFFFFFFFC00003FFFFFFFFFF000007FFFFFFFFFC00000FFFFFFFFFF000001FFFFFFFFFC000003FFFFFFFFE0000007FFFFFFFF8000000FFF,
		ram_block1a_7.mem_init1 = 2048'hFC000000003FFFFFFF000000001FFFFFFFC00000000FFFFFFFF000000007FFFFFFFC00000003FFFFFFFF00000001FFFFFFFFC0000000FFFFFFFFF00000007FFFFFFFFC0000003FFFFFFFFF8000001FFFFFFFFFE0000007FFFFFFFFF8000003FFFFFFFFFE000001FFFFFFFFFF800000FFFFFFFFFFE000007FFFFFFFFFF800003FFFFFFFFFFE00001FFFFFFFFFFF80000FFFFFFFFFFFE00007FFFFFFFFFFF80003FFFFFFFFFFFE0001FFFFFFFFFFFF8000FFFFFFFFFFFFE000FFFFFFFFFFFFF8007FFFFFFFFFFFFE0001FFFFFFFFFFFF800007FFFFFFFFFFE000000FFFFFFFFFF80000003FFFFFFFFE000000007FFFFFFF0000000001FFFFFF000000000007FFFF,
		ram_block1a_7.operation_mode = "rom",
		ram_block1a_7.port_a_address_clear = "none",
		ram_block1a_7.port_a_address_width = 12,
		ram_block1a_7.port_a_data_out_clear = "none",
		ram_block1a_7.port_a_data_out_clock = "none",
		ram_block1a_7.port_a_data_width = 1,
		ram_block1a_7.port_a_first_address = 0,
		ram_block1a_7.port_a_first_bit_number = 7,
		ram_block1a_7.port_a_last_address = 4095,
		ram_block1a_7.port_a_logical_ram_depth = 4096,
		ram_block1a_7.port_a_logical_ram_width = 12,
		ram_block1a_7.ram_block_type = "AUTO",
		ram_block1a_7.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_8
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_8portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_8.clk0_core_clock_enable = "none",
		ram_block1a_8.clk0_input_clock_enable = "none",
		ram_block1a_8.connectivity_checking = "OFF",
		ram_block1a_8.init_file = "../ip/Boxtheta_Rom/Boxtheta_rom.mif",
		ram_block1a_8.init_file_layout = "port_a",
		ram_block1a_8.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_8.mem_init0 = 2048'hFFFFFFFFFFFFF000FFFFFFFFFFFFFFC0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFE0FFFFFFFFFFFFFF80FFFFFFFFFFFFFC00FFFFFFFFFFFFF000FFFFFFFFFFFFC000FFFFFFFFFFFF0000FFFFFFFFFFFC0000FFFFFFFFFFF00000FFFFFFFFFFC00000FFFFFFFFFF000000FFFFFFFFFC000000FFFFFFFFF0000000FFFFFFFFC0000000FFFFFFFF00000000FFFFFFFC00000000FFFFFFE000000000FFFFFF8000000000,
		ram_block1a_8.mem_init1 = 2048'h00000000003FFFFF00000000001FFFFF00000000000FFFFF000000000007FFFF000000000003FFFF000000000001FFFF000000000000FFFF0000000000007FFF0000000000003FFF0000000000001FFF00000000000007FF00000000000003FF00000000000001FF00000000000000FF000000000000007F000000000000003F000000000000001F000000000000000F0000000000000007000000000000000300000000000000010000000000000000000000000000000000000000000000008000000000000000FE00000000000000FFF8000000000000FFFFF00000000000FFFFFFC000000000FFFFFFFF80000000FFFFFFFFFE000000FFFFFFFFFFF80000,
		ram_block1a_8.operation_mode = "rom",
		ram_block1a_8.port_a_address_clear = "none",
		ram_block1a_8.port_a_address_width = 12,
		ram_block1a_8.port_a_data_out_clear = "none",
		ram_block1a_8.port_a_data_out_clock = "none",
		ram_block1a_8.port_a_data_width = 1,
		ram_block1a_8.port_a_first_address = 0,
		ram_block1a_8.port_a_first_bit_number = 8,
		ram_block1a_8.port_a_last_address = 4095,
		ram_block1a_8.port_a_logical_ram_depth = 4096,
		ram_block1a_8.port_a_logical_ram_width = 12,
		ram_block1a_8.ram_block_type = "AUTO",
		ram_block1a_8.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_9
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_9portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_9.clk0_core_clock_enable = "none",
		ram_block1a_9.clk0_input_clock_enable = "none",
		ram_block1a_9.connectivity_checking = "OFF",
		ram_block1a_9.init_file = "../ip/Boxtheta_Rom/Boxtheta_rom.mif",
		ram_block1a_9.init_file_layout = "port_a",
		ram_block1a_9.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_9.mem_init0 = 2048'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFE0FFFFFFFFFFFFFF80FFFFFFFFFFFFFC00FFFFFFFFFFFFF000FFFFFFFFFFFFC000FFFFFFFFFFFF0000FFFFFFFFFFFC0000FFFFFFFFFFF00000FFFFFFFFFFC00000FFFFFFFFFF000000FFFFFFFFFC000000FFFFFFFFF0000000FFFFFFFFC0000000FFFFFFFF00000000FFFFFFFC00000000FFFFFFE000000000FFFFFF8000000000,
		ram_block1a_9.mem_init1 = 2048'hFFFFFFFFFFC00000FFFFFFFFFFE00000FFFFFFFFFFF00000FFFFFFFFFFF80000FFFFFFFFFFFC0000FFFFFFFFFFFE0000FFFFFFFFFFFF0000FFFFFFFFFFFF8000FFFFFFFFFFFFC000FFFFFFFFFFFFE000FFFFFFFFFFFFF800FFFFFFFFFFFFFC00FFFFFFFFFFFFFE00FFFFFFFFFFFFFF00FFFFFFFFFFFFFF80FFFFFFFFFFFFFFC0FFFFFFFFFFFFFFE0FFFFFFFFFFFFFFF0FFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,
		ram_block1a_9.operation_mode = "rom",
		ram_block1a_9.port_a_address_clear = "none",
		ram_block1a_9.port_a_address_width = 12,
		ram_block1a_9.port_a_data_out_clear = "none",
		ram_block1a_9.port_a_data_out_clock = "none",
		ram_block1a_9.port_a_data_width = 1,
		ram_block1a_9.port_a_first_address = 0,
		ram_block1a_9.port_a_first_bit_number = 9,
		ram_block1a_9.port_a_last_address = 4095,
		ram_block1a_9.port_a_logical_ram_depth = 4096,
		ram_block1a_9.port_a_logical_ram_width = 12,
		ram_block1a_9.ram_block_type = "AUTO",
		ram_block1a_9.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_10
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_10portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_10.clk0_core_clock_enable = "none",
		ram_block1a_10.clk0_input_clock_enable = "none",
		ram_block1a_10.connectivity_checking = "OFF",
		ram_block1a_10.init_file = "../ip/Boxtheta_Rom/Boxtheta_rom.mif",
		ram_block1a_10.init_file_layout = "port_a",
		ram_block1a_10.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_10.mem_init0 = 2048'h000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000007000000000000001F000000000000007F00000000000003FF0000000000000FFF0000000000003FFF000000000000FFFF000000000003FFFF00000000000FFFFF00000000003FFFFF0000000000FFFFFF0000000003FFFFFF000000000FFFFFFF000000003FFFFFFF00000000FFFFFFFF00000003FFFFFFFF0000001FFFFFFFFF0000007FFFFFFFFF,
		ram_block1a_10.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_10.operation_mode = "rom",
		ram_block1a_10.port_a_address_clear = "none",
		ram_block1a_10.port_a_address_width = 12,
		ram_block1a_10.port_a_data_out_clear = "none",
		ram_block1a_10.port_a_data_out_clock = "none",
		ram_block1a_10.port_a_data_width = 1,
		ram_block1a_10.port_a_first_address = 0,
		ram_block1a_10.port_a_first_bit_number = 10,
		ram_block1a_10.port_a_last_address = 4095,
		ram_block1a_10.port_a_logical_ram_depth = 4096,
		ram_block1a_10.port_a_logical_ram_width = 12,
		ram_block1a_10.ram_block_type = "AUTO",
		ram_block1a_10.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_11
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_11portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_11.clk0_core_clock_enable = "none",
		ram_block1a_11.clk0_input_clock_enable = "none",
		ram_block1a_11.connectivity_checking = "OFF",
		ram_block1a_11.init_file = "../ip/Boxtheta_Rom/Boxtheta_rom.mif",
		ram_block1a_11.init_file_layout = "port_a",
		ram_block1a_11.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_11.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_11.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_11.operation_mode = "rom",
		ram_block1a_11.port_a_address_clear = "none",
		ram_block1a_11.port_a_address_width = 12,
		ram_block1a_11.port_a_data_out_clear = "none",
		ram_block1a_11.port_a_data_out_clock = "none",
		ram_block1a_11.port_a_data_width = 1,
		ram_block1a_11.port_a_first_address = 0,
		ram_block1a_11.port_a_first_bit_number = 11,
		ram_block1a_11.port_a_last_address = 4095,
		ram_block1a_11.port_a_logical_ram_depth = 4096,
		ram_block1a_11.port_a_logical_ram_width = 12,
		ram_block1a_11.ram_block_type = "AUTO",
		ram_block1a_11.lpm_type = "cycloneive_ram_block";
	assign
		address_a_wire = address_a,
		q_a = {wire_ram_block1a_11portadataout[0], wire_ram_block1a_10portadataout[0], wire_ram_block1a_9portadataout[0], wire_ram_block1a_8portadataout[0], wire_ram_block1a_7portadataout[0], wire_ram_block1a_6portadataout[0], wire_ram_block1a_5portadataout[0], wire_ram_block1a_4portadataout[0], wire_ram_block1a_3portadataout[0], wire_ram_block1a_2portadataout[0], wire_ram_block1a_1portadataout[0], wire_ram_block1a_0portadataout[0]};
endmodule //Boxtheta_Rom_altsyncram
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module Boxtheta_Rom (
	address,
	clock,
	q)/* synthesis synthesis_clearbox = 1 */;

	input	[11:0]  address;
	input	  clock;
	output	[11:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1	  clock;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire [11:0] sub_wire0;
	wire [11:0] q = sub_wire0[11:0];

	Boxtheta_Rom_altsyncram	Boxtheta_Rom_altsyncram_component (
				.address_a (address),
				.clock0 (clock),
				.q_a (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ADDRESSSTALL_A NUMERIC "0"
// Retrieval info: PRIVATE: AclrAddr NUMERIC "0"
// Retrieval info: PRIVATE: AclrByte NUMERIC "0"
// Retrieval info: PRIVATE: AclrOutput NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_ENABLE NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_SIZE NUMERIC "8"
// Retrieval info: PRIVATE: BlankMemory NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_INPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_OUTPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: Clken NUMERIC "0"
// Retrieval info: PRIVATE: IMPLEMENT_IN_LES NUMERIC "0"
// Retrieval info: PRIVATE: INIT_FILE_LAYOUT STRING "PORT_A"
// Retrieval info: PRIVATE: INIT_TO_SIM_X NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone IV E"
// Retrieval info: PRIVATE: JTAG_ENABLED NUMERIC "0"
// Retrieval info: PRIVATE: JTAG_ID STRING "NONE"
// Retrieval info: PRIVATE: MAXIMUM_DEPTH NUMERIC "0"
// Retrieval info: PRIVATE: MIFfilename STRING "../ip/Boxtheta_Rom/Boxtheta_rom.mif"
// Retrieval info: PRIVATE: NUMWORDS_A NUMERIC "4096"
// Retrieval info: PRIVATE: RAM_BLOCK_TYPE NUMERIC "0"
// Retrieval info: PRIVATE: RegAddr NUMERIC "1"
// Retrieval info: PRIVATE: RegOutput NUMERIC "0"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: SingleClock NUMERIC "1"
// Retrieval info: PRIVATE: UseDQRAM NUMERIC "0"
// Retrieval info: PRIVATE: WidthAddr NUMERIC "12"
// Retrieval info: PRIVATE: WidthData NUMERIC "12"
// Retrieval info: PRIVATE: rden NUMERIC "0"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: ADDRESS_ACLR_A STRING "NONE"
// Retrieval info: CONSTANT: CLOCK_ENABLE_INPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: CLOCK_ENABLE_OUTPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: INIT_FILE STRING "../ip/Boxtheta_Rom/Boxtheta_rom.mif"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone IV E"
// Retrieval info: CONSTANT: LPM_HINT STRING "ENABLE_RUNTIME_MOD=NO"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altsyncram"
// Retrieval info: CONSTANT: NUMWORDS_A NUMERIC "4096"
// Retrieval info: CONSTANT: OPERATION_MODE STRING "ROM"
// Retrieval info: CONSTANT: OUTDATA_ACLR_A STRING "NONE"
// Retrieval info: CONSTANT: OUTDATA_REG_A STRING "UNREGISTERED"
// Retrieval info: CONSTANT: WIDTHAD_A NUMERIC "12"
// Retrieval info: CONSTANT: WIDTH_A NUMERIC "12"
// Retrieval info: CONSTANT: WIDTH_BYTEENA_A NUMERIC "1"
// Retrieval info: USED_PORT: address 0 0 12 0 INPUT NODEFVAL "address[11..0]"
// Retrieval info: USED_PORT: clock 0 0 0 0 INPUT VCC "clock"
// Retrieval info: USED_PORT: q 0 0 12 0 OUTPUT NODEFVAL "q[11..0]"
// Retrieval info: CONNECT: @address_a 0 0 12 0 address 0 0 12 0
// Retrieval info: CONNECT: @clock0 0 0 0 0 clock 0 0 0 0
// Retrieval info: CONNECT: q 0 0 12 0 @q_a 0 0 12 0
// Retrieval info: GEN_FILE: TYPE_NORMAL Boxtheta_Rom.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL Boxtheta_Rom.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL Boxtheta_Rom.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL Boxtheta_Rom.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL Boxtheta_Rom_inst.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL Boxtheta_Rom_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL Boxtheta_Rom_syn.v TRUE
// Retrieval info: LIB_FILE: altera_mf
