// megafunction wizard: %ROM: 1-PORT%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altsyncram 

// ============================================================
// File Name: Robot_Rom.v
// Megafunction Name(s):
// 			altsyncram
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 18.1.0 Build 625 09/12/2018 SJ Lite Edition
// ************************************************************


//Copyright (C) 2018  Intel Corporation. All rights reserved.
//Your use of Intel Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Intel Program License 
//Subscription Agreement, the Intel Quartus Prime License Agreement,
//the Intel FPGA IP License Agreement, or other applicable license
//agreement, including, without limitation, that your use is for
//the sole purpose of programming logic devices manufactured by
//Intel and sold by Intel or its authorized distributors.  Please
//refer to the applicable agreement for further details.


//altsyncram ADDRESS_ACLR_A="NONE" CLOCK_ENABLE_INPUT_A="BYPASS" CLOCK_ENABLE_OUTPUT_A="BYPASS" DEVICE_FAMILY="Cyclone IV E" ENABLE_RUNTIME_MOD="NO" INIT_FILE="../../ip/Robot_Rom/arm_rom.mif" NUMWORDS_A=1024 OPERATION_MODE="ROM" OUTDATA_ACLR_A="NONE" OUTDATA_REG_A="UNREGISTERED" WIDTH_A=36 WIDTH_BYTEENA_A=1 WIDTHAD_A=10 address_a clock0 q_a
//VERSION_BEGIN 18.1 cbx_altera_syncram_nd_impl 2018:09:12:13:04:24:SJ cbx_altsyncram 2018:09:12:13:04:24:SJ cbx_cycloneii 2018:09:12:13:04:24:SJ cbx_lpm_add_sub 2018:09:12:13:04:24:SJ cbx_lpm_compare 2018:09:12:13:04:24:SJ cbx_lpm_decode 2018:09:12:13:04:24:SJ cbx_lpm_mux 2018:09:12:13:04:24:SJ cbx_mgl 2018:09:12:13:10:36:SJ cbx_nadder 2018:09:12:13:04:24:SJ cbx_stratix 2018:09:12:13:04:24:SJ cbx_stratixii 2018:09:12:13:04:24:SJ cbx_stratixiii 2018:09:12:13:04:24:SJ cbx_stratixv 2018:09:12:13:04:24:SJ cbx_util_mgl 2018:09:12:13:04:24:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = M9K 4 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"OPTIMIZE_POWER_DURING_SYNTHESIS=NORMAL_COMPILATION"} *)
module  Robot_Rom_altsyncram
	( 
	address_a,
	clock0,
	q_a) /* synthesis synthesis_clearbox=1 */;
	input   [9:0]  address_a;
	input   clock0;
	output   [35:0]  q_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   clock0;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]   wire_ram_block1a_0portadataout;
	wire  [0:0]   wire_ram_block1a_1portadataout;
	wire  [0:0]   wire_ram_block1a_2portadataout;
	wire  [0:0]   wire_ram_block1a_3portadataout;
	wire  [0:0]   wire_ram_block1a_4portadataout;
	wire  [0:0]   wire_ram_block1a_5portadataout;
	wire  [0:0]   wire_ram_block1a_6portadataout;
	wire  [0:0]   wire_ram_block1a_7portadataout;
	wire  [0:0]   wire_ram_block1a_8portadataout;
	wire  [0:0]   wire_ram_block1a_9portadataout;
	wire  [0:0]   wire_ram_block1a_10portadataout;
	wire  [0:0]   wire_ram_block1a_11portadataout;
	wire  [0:0]   wire_ram_block1a_12portadataout;
	wire  [0:0]   wire_ram_block1a_13portadataout;
	wire  [0:0]   wire_ram_block1a_14portadataout;
	wire  [0:0]   wire_ram_block1a_15portadataout;
	wire  [0:0]   wire_ram_block1a_16portadataout;
	wire  [0:0]   wire_ram_block1a_17portadataout;
	wire  [0:0]   wire_ram_block1a_18portadataout;
	wire  [0:0]   wire_ram_block1a_19portadataout;
	wire  [0:0]   wire_ram_block1a_20portadataout;
	wire  [0:0]   wire_ram_block1a_21portadataout;
	wire  [0:0]   wire_ram_block1a_22portadataout;
	wire  [0:0]   wire_ram_block1a_23portadataout;
	wire  [0:0]   wire_ram_block1a_24portadataout;
	wire  [0:0]   wire_ram_block1a_25portadataout;
	wire  [0:0]   wire_ram_block1a_26portadataout;
	wire  [0:0]   wire_ram_block1a_27portadataout;
	wire  [0:0]   wire_ram_block1a_28portadataout;
	wire  [0:0]   wire_ram_block1a_29portadataout;
	wire  [0:0]   wire_ram_block1a_30portadataout;
	wire  [0:0]   wire_ram_block1a_31portadataout;
	wire  [0:0]   wire_ram_block1a_32portadataout;
	wire  [0:0]   wire_ram_block1a_33portadataout;
	wire  [0:0]   wire_ram_block1a_34portadataout;
	wire  [0:0]   wire_ram_block1a_35portadataout;
	wire  [9:0]  address_a_wire;

	cycloneive_ram_block   ram_block1a_0
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_0portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_0.clk0_core_clock_enable = "none",
		ram_block1a_0.clk0_input_clock_enable = "none",
		ram_block1a_0.connectivity_checking = "OFF",
		ram_block1a_0.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_0.init_file_layout = "port_a",
		ram_block1a_0.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_0.mem_init0 = 1024'h000000000000000000000000000000000000000000000000000000000000448A98FE1CDB4AAB5A6CC71F807E18C96AAA4CE00392A9800000000000000000000000000000000000000000000000000000000000000000000000000000000018AA61FF0E66DA55552926663C0FE07192555330076A60C000000000000000000000,
		ram_block1a_0.operation_mode = "rom",
		ram_block1a_0.port_a_address_clear = "none",
		ram_block1a_0.port_a_address_width = 10,
		ram_block1a_0.port_a_data_out_clear = "none",
		ram_block1a_0.port_a_data_out_clock = "none",
		ram_block1a_0.port_a_data_width = 1,
		ram_block1a_0.port_a_first_address = 0,
		ram_block1a_0.port_a_first_bit_number = 0,
		ram_block1a_0.port_a_last_address = 1023,
		ram_block1a_0.port_a_logical_ram_depth = 1024,
		ram_block1a_0.port_a_logical_ram_width = 36,
		ram_block1a_0.ram_block_type = "AUTO",
		ram_block1a_0.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_1
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_1portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_1.clk0_core_clock_enable = "none",
		ram_block1a_1.clk0_input_clock_enable = "none",
		ram_block1a_1.connectivity_checking = "OFF",
		ram_block1a_1.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_1.init_file_layout = "port_a",
		ram_block1a_1.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_1.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000006C0CD2AAB5B6D998C61C3F007F801F0E7333694AA9499860000000000000000000000000000000000000000000000000000000000000000000000000000000007F334AAAA52DB6CCCCE71E1E03FFFF81E3999A5AAD261F0000000000000000000000,
		ram_block1a_1.operation_mode = "rom",
		ram_block1a_1.port_a_address_clear = "none",
		ram_block1a_1.port_a_address_width = 10,
		ram_block1a_1.port_a_data_out_clear = "none",
		ram_block1a_1.port_a_data_out_clock = "none",
		ram_block1a_1.port_a_data_width = 1,
		ram_block1a_1.port_a_first_address = 0,
		ram_block1a_1.port_a_first_bit_number = 1,
		ram_block1a_1.port_a_last_address = 1023,
		ram_block1a_1.port_a_logical_ram_depth = 1024,
		ram_block1a_1.port_a_logical_ram_width = 36,
		ram_block1a_1.ram_block_type = "AUTO",
		ram_block1a_1.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_2
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_2portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_2.clk0_core_clock_enable = "none",
		ram_block1a_2.clk0_input_clock_enable = "none",
		ram_block1a_2.connectivity_checking = "OFF",
		ram_block1a_2.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_2.init_file_layout = "port_a",
		ram_block1a_2.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_2.mem_init0 = 1024'h000000000000000000000000000000000000000000000000000000000000095A49998C71C787C1FC00FFFFFFE00F83C38E73326D2D40000000000000000000000000000000000000000000000000000000000000000000000000000000002A96D9999CE38E3C3C1F01FE00000001FC1E1C63364B554000000000000000000000,
		ram_block1a_2.operation_mode = "rom",
		ram_block1a_2.port_a_address_clear = "none",
		ram_block1a_2.port_a_address_width = 10,
		ram_block1a_2.port_a_data_out_clear = "none",
		ram_block1a_2.port_a_data_out_clock = "none",
		ram_block1a_2.port_a_data_width = 1,
		ram_block1a_2.port_a_first_address = 0,
		ram_block1a_2.port_a_first_bit_number = 2,
		ram_block1a_2.port_a_last_address = 1023,
		ram_block1a_2.port_a_logical_ram_depth = 1024,
		ram_block1a_2.port_a_logical_ram_width = 36,
		ram_block1a_2.ram_block_type = "AUTO",
		ram_block1a_2.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_3
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_3portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_3.clk0_core_clock_enable = "none",
		ram_block1a_3.clk0_input_clock_enable = "none",
		ram_block1a_3.connectivity_checking = "OFF",
		ram_block1a_3.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_3.init_file_layout = "port_a",
		ram_block1a_3.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_3.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000005B39C78783F03F803FFC00000000000FFC03F07C3C71CE60000000000000000000000000000000000000000000000000000000000000000000000000000000006671C78783E07E03FC00FFFE00000001FFE01F83C78C666000000000000000000000,
		ram_block1a_3.operation_mode = "rom",
		ram_block1a_3.port_a_address_clear = "none",
		ram_block1a_3.port_a_address_width = 10,
		ram_block1a_3.port_a_data_out_clear = "none",
		ram_block1a_3.port_a_data_out_clock = "none",
		ram_block1a_3.port_a_data_width = 1,
		ram_block1a_3.port_a_first_address = 0,
		ram_block1a_3.port_a_first_bit_number = 3,
		ram_block1a_3.port_a_last_address = 1023,
		ram_block1a_3.port_a_logical_ram_depth = 1024,
		ram_block1a_3.port_a_logical_ram_width = 36,
		ram_block1a_3.ram_block_type = "AUTO",
		ram_block1a_3.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_4
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_4portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_4.clk0_core_clock_enable = "none",
		ram_block1a_4.clk0_input_clock_enable = "none",
		ram_block1a_4.connectivity_checking = "OFF",
		ram_block1a_4.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_4.init_file_layout = "port_a",
		ram_block1a_4.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_4.mem_init0 = 1024'h00000000000000000000000000000000000000000000000000000000000038F83F807FF0007FFFFC00000000000FFFFC007FC07E0F800000000000000000000000000000000000000000000000000000000000000000000000000000000061F03F807FE001FFFC000001FFFFFFFE00001FFC07F0786000000000000000000000,
		ram_block1a_4.operation_mode = "rom",
		ram_block1a_4.port_a_address_clear = "none",
		ram_block1a_4.port_a_address_width = 10,
		ram_block1a_4.port_a_data_out_clear = "none",
		ram_block1a_4.port_a_data_out_clock = "none",
		ram_block1a_4.port_a_data_width = 1,
		ram_block1a_4.port_a_first_address = 0,
		ram_block1a_4.port_a_first_bit_number = 4,
		ram_block1a_4.port_a_last_address = 1023,
		ram_block1a_4.port_a_logical_ram_depth = 1024,
		ram_block1a_4.port_a_logical_ram_width = 36,
		ram_block1a_4.ram_block_type = "AUTO",
		ram_block1a_4.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_5
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_5portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_5.clk0_core_clock_enable = "none",
		ram_block1a_5.clk0_input_clock_enable = "none",
		ram_block1a_5.connectivity_checking = "OFF",
		ram_block1a_5.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_5.init_file_layout = "port_a",
		ram_block1a_5.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_5.mem_init0 = 1024'h00000000000000000000000000000000000000000000000000000000000007F8007FFFF000000003FFFFFFFFFFF00000007FFF800FE0000000000000000000000000000000000000000000000000000000000000000000000000000000001FF0007FFFE0000003FFFFFFFFFFFFFFFFFFE00007FF806000000000000000000000,
		ram_block1a_5.operation_mode = "rom",
		ram_block1a_5.port_a_address_clear = "none",
		ram_block1a_5.port_a_address_width = 10,
		ram_block1a_5.port_a_data_out_clear = "none",
		ram_block1a_5.port_a_data_out_clock = "none",
		ram_block1a_5.port_a_data_width = 1,
		ram_block1a_5.port_a_first_address = 0,
		ram_block1a_5.port_a_first_bit_number = 5,
		ram_block1a_5.port_a_last_address = 1023,
		ram_block1a_5.port_a_logical_ram_depth = 1024,
		ram_block1a_5.port_a_logical_ram_width = 36,
		ram_block1a_5.ram_block_type = "AUTO",
		ram_block1a_5.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_6
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_6portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_6.clk0_core_clock_enable = "none",
		ram_block1a_6.clk0_input_clock_enable = "none",
		ram_block1a_6.connectivity_checking = "OFF",
		ram_block1a_6.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_6.init_file_layout = "port_a",
		ram_block1a_6.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_6.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000007FFFFFFF0000000000000000000000000007FFFFFF000000000000000000000000000000000000000000000000000000000000000000000000000000000007FF00000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF800006000000000000000000000,
		ram_block1a_6.operation_mode = "rom",
		ram_block1a_6.port_a_address_clear = "none",
		ram_block1a_6.port_a_address_width = 10,
		ram_block1a_6.port_a_data_out_clear = "none",
		ram_block1a_6.port_a_data_out_clock = "none",
		ram_block1a_6.port_a_data_width = 1,
		ram_block1a_6.port_a_first_address = 0,
		ram_block1a_6.port_a_first_bit_number = 6,
		ram_block1a_6.port_a_last_address = 1023,
		ram_block1a_6.port_a_logical_ram_depth = 1024,
		ram_block1a_6.port_a_logical_ram_width = 36,
		ram_block1a_6.ram_block_type = "AUTO",
		ram_block1a_6.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_7
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_7portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_7.clk0_core_clock_enable = "none",
		ram_block1a_7.clk0_input_clock_enable = "none",
		ram_block1a_7.connectivity_checking = "OFF",
		ram_block1a_7.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_7.init_file_layout = "port_a",
		ram_block1a_7.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_7.mem_init0 = 1024'h00000000000000000000000000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFF800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000000000000000000000,
		ram_block1a_7.operation_mode = "rom",
		ram_block1a_7.port_a_address_clear = "none",
		ram_block1a_7.port_a_address_width = 10,
		ram_block1a_7.port_a_data_out_clear = "none",
		ram_block1a_7.port_a_data_out_clock = "none",
		ram_block1a_7.port_a_data_width = 1,
		ram_block1a_7.port_a_first_address = 0,
		ram_block1a_7.port_a_first_bit_number = 7,
		ram_block1a_7.port_a_last_address = 1023,
		ram_block1a_7.port_a_logical_ram_depth = 1024,
		ram_block1a_7.port_a_logical_ram_width = 36,
		ram_block1a_7.ram_block_type = "AUTO",
		ram_block1a_7.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_8
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_8portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_8.clk0_core_clock_enable = "none",
		ram_block1a_8.clk0_input_clock_enable = "none",
		ram_block1a_8.connectivity_checking = "OFF",
		ram_block1a_8.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_8.init_file_layout = "port_a",
		ram_block1a_8.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_8.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE0000000000000000000000000000000000000000000000000000000000000000000000000000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE000000000000000000000,
		ram_block1a_8.operation_mode = "rom",
		ram_block1a_8.port_a_address_clear = "none",
		ram_block1a_8.port_a_address_width = 10,
		ram_block1a_8.port_a_data_out_clear = "none",
		ram_block1a_8.port_a_data_out_clock = "none",
		ram_block1a_8.port_a_data_width = 1,
		ram_block1a_8.port_a_first_address = 0,
		ram_block1a_8.port_a_first_bit_number = 8,
		ram_block1a_8.port_a_last_address = 1023,
		ram_block1a_8.port_a_logical_ram_depth = 1024,
		ram_block1a_8.port_a_logical_ram_width = 36,
		ram_block1a_8.ram_block_type = "AUTO",
		ram_block1a_8.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_9
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_9portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_9.clk0_core_clock_enable = "none",
		ram_block1a_9.clk0_input_clock_enable = "none",
		ram_block1a_9.connectivity_checking = "OFF",
		ram_block1a_9.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_9.init_file_layout = "port_a",
		ram_block1a_9.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_9.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE0000000000000000000000000000000000000000000000000000000000000000000000000000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE000000000000000000000,
		ram_block1a_9.operation_mode = "rom",
		ram_block1a_9.port_a_address_clear = "none",
		ram_block1a_9.port_a_address_width = 10,
		ram_block1a_9.port_a_data_out_clear = "none",
		ram_block1a_9.port_a_data_out_clock = "none",
		ram_block1a_9.port_a_data_width = 1,
		ram_block1a_9.port_a_first_address = 0,
		ram_block1a_9.port_a_first_bit_number = 9,
		ram_block1a_9.port_a_last_address = 1023,
		ram_block1a_9.port_a_logical_ram_depth = 1024,
		ram_block1a_9.port_a_logical_ram_width = 36,
		ram_block1a_9.ram_block_type = "AUTO",
		ram_block1a_9.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_10
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_10portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_10.clk0_core_clock_enable = "none",
		ram_block1a_10.clk0_input_clock_enable = "none",
		ram_block1a_10.connectivity_checking = "OFF",
		ram_block1a_10.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_10.init_file_layout = "port_a",
		ram_block1a_10.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_10.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_10.operation_mode = "rom",
		ram_block1a_10.port_a_address_clear = "none",
		ram_block1a_10.port_a_address_width = 10,
		ram_block1a_10.port_a_data_out_clear = "none",
		ram_block1a_10.port_a_data_out_clock = "none",
		ram_block1a_10.port_a_data_width = 1,
		ram_block1a_10.port_a_first_address = 0,
		ram_block1a_10.port_a_first_bit_number = 10,
		ram_block1a_10.port_a_last_address = 1023,
		ram_block1a_10.port_a_logical_ram_depth = 1024,
		ram_block1a_10.port_a_logical_ram_width = 36,
		ram_block1a_10.ram_block_type = "AUTO",
		ram_block1a_10.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_11
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_11portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_11.clk0_core_clock_enable = "none",
		ram_block1a_11.clk0_input_clock_enable = "none",
		ram_block1a_11.connectivity_checking = "OFF",
		ram_block1a_11.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_11.init_file_layout = "port_a",
		ram_block1a_11.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_11.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_11.operation_mode = "rom",
		ram_block1a_11.port_a_address_clear = "none",
		ram_block1a_11.port_a_address_width = 10,
		ram_block1a_11.port_a_data_out_clear = "none",
		ram_block1a_11.port_a_data_out_clock = "none",
		ram_block1a_11.port_a_data_width = 1,
		ram_block1a_11.port_a_first_address = 0,
		ram_block1a_11.port_a_first_bit_number = 11,
		ram_block1a_11.port_a_last_address = 1023,
		ram_block1a_11.port_a_logical_ram_depth = 1024,
		ram_block1a_11.port_a_logical_ram_width = 36,
		ram_block1a_11.ram_block_type = "AUTO",
		ram_block1a_11.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_12
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_12portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_12.clk0_core_clock_enable = "none",
		ram_block1a_12.clk0_input_clock_enable = "none",
		ram_block1a_12.connectivity_checking = "OFF",
		ram_block1a_12.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_12.init_file_layout = "port_a",
		ram_block1a_12.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_12.mem_init0 = 1024'h00000000000000000000000000000000000000000000000000000000000039CD41B2601CCA54A499CF0FF00FFC1E1C718C6660000000000000000000000000000000000000000000000000000000000000000000000000000000000000003B980AB783CCB555A4998E3C1FE000007FFC00000000000000000000000000000000,
		ram_block1a_12.operation_mode = "rom",
		ram_block1a_12.port_a_address_clear = "none",
		ram_block1a_12.port_a_address_width = 10,
		ram_block1a_12.port_a_data_out_clear = "none",
		ram_block1a_12.port_a_data_out_clock = "none",
		ram_block1a_12.port_a_data_width = 1,
		ram_block1a_12.port_a_first_address = 0,
		ram_block1a_12.port_a_first_bit_number = 12,
		ram_block1a_12.port_a_last_address = 1023,
		ram_block1a_12.port_a_logical_ram_depth = 1024,
		ram_block1a_12.port_a_logical_ram_width = 36,
		ram_block1a_12.ram_block_type = "AUTO",
		ram_block1a_12.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_13
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_13portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_13.clk0_core_clock_enable = "none",
		ram_block1a_13.clk0_input_clock_enable = "none",
		ram_block1a_13.connectivity_checking = "OFF",
		ram_block1a_13.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_13.init_file_layout = "port_a",
		ram_block1a_13.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_13.mem_init0 = 1024'h00000000000000000000000000000000000000000000000000000000000063EB3E3B4AB5A6CC6387C0FFF00FFFE01F81F078700000000000000000000000000000000000000000000000000000000000000000000000000000000000000002B80CDAD6A593339C787E03FFE000007FFFFE000000000000000000000000000000,
		ram_block1a_13.operation_mode = "rom",
		ram_block1a_13.port_a_address_clear = "none",
		ram_block1a_13.port_a_address_width = 10,
		ram_block1a_13.port_a_data_out_clear = "none",
		ram_block1a_13.port_a_data_out_clock = "none",
		ram_block1a_13.port_a_data_width = 1,
		ram_block1a_13.port_a_first_address = 0,
		ram_block1a_13.port_a_first_bit_number = 13,
		ram_block1a_13.port_a_last_address = 1023,
		ram_block1a_13.port_a_logical_ram_depth = 1024,
		ram_block1a_13.port_a_logical_ram_width = 36,
		ram_block1a_13.ram_block_type = "AUTO",
		ram_block1a_13.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_14
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_14portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_14.clk0_core_clock_enable = "none",
		ram_block1a_14.clk0_input_clock_enable = "none",
		ram_block1a_14.connectivity_checking = "OFF",
		ram_block1a_14.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_14.init_file_layout = "port_a",
		ram_block1a_14.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_14.mem_init0 = 1024'h00000000000000000000000000000000000000000000000000000000000022A7003C7326CB694AD56AAAA55AAAAAB554AAD52FFFFFE00000000000000000000000000000000000000000000000000000000000000000000000000000000056780F1CE4C925A52952AB55554AAAAAD55555FFFFFFFFE000000000000000000000,
		ram_block1a_14.operation_mode = "rom",
		ram_block1a_14.port_a_address_clear = "none",
		ram_block1a_14.port_a_address_width = 10,
		ram_block1a_14.port_a_data_out_clear = "none",
		ram_block1a_14.port_a_data_out_clock = "none",
		ram_block1a_14.port_a_data_width = 1,
		ram_block1a_14.port_a_first_address = 0,
		ram_block1a_14.port_a_first_bit_number = 14,
		ram_block1a_14.port_a_last_address = 1023,
		ram_block1a_14.port_a_logical_ram_depth = 1024,
		ram_block1a_14.port_a_logical_ram_width = 36,
		ram_block1a_14.ram_block_type = "AUTO",
		ram_block1a_14.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_15
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_15portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_15.clk0_core_clock_enable = "none",
		ram_block1a_15.clk0_input_clock_enable = "none",
		ram_block1a_15.connectivity_checking = "OFF",
		ram_block1a_15.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_15.init_file_layout = "port_a",
		ram_block1a_15.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_15.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000001CCA556AD6925924D9B326666CC66666733399CCE00000000000000000000000000000000000000000000000000000000000000000000000000000000000000064AD5AB5ADA4936C9B3666CCCCD99999CCCCCC000000000000000000000000000000,
		ram_block1a_15.operation_mode = "rom",
		ram_block1a_15.port_a_address_clear = "none",
		ram_block1a_15.port_a_address_width = 10,
		ram_block1a_15.port_a_data_out_clear = "none",
		ram_block1a_15.port_a_data_out_clock = "none",
		ram_block1a_15.port_a_data_width = 1,
		ram_block1a_15.port_a_first_address = 0,
		ram_block1a_15.port_a_first_bit_number = 15,
		ram_block1a_15.port_a_last_address = 1023,
		ram_block1a_15.port_a_logical_ram_depth = 1024,
		ram_block1a_15.port_a_logical_ram_width = 36,
		ram_block1a_15.ram_block_type = "AUTO",
		ram_block1a_15.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_16
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_16portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_16.clk0_core_clock_enable = "none",
		ram_block1a_16.clk0_input_clock_enable = "none",
		ram_block1a_16.connectivity_checking = "OFF",
		ram_block1a_16.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_16.init_file_layout = "port_a",
		ram_block1a_16.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_16.mem_init0 = 1024'h00000000000000000000000000000000000000000000000000000000000055A6CCE6318E38E3C78F1E1E1C3E1E1E0F0F87C3E0000000000000000000000000000000000000000000000000000000000000000000000000000000000000002D9B398C639C70E3870E1E3C3C3878783C3C3C000000000000000000000000000000,
		ram_block1a_16.operation_mode = "rom",
		ram_block1a_16.port_a_address_clear = "none",
		ram_block1a_16.port_a_address_width = 10,
		ram_block1a_16.port_a_data_out_clear = "none",
		ram_block1a_16.port_a_data_out_clock = "none",
		ram_block1a_16.port_a_data_width = 1,
		ram_block1a_16.port_a_first_address = 0,
		ram_block1a_16.port_a_first_bit_number = 16,
		ram_block1a_16.port_a_last_address = 1023,
		ram_block1a_16.port_a_logical_ram_depth = 1024,
		ram_block1a_16.port_a_logical_ram_width = 36,
		ram_block1a_16.ram_block_type = "AUTO",
		ram_block1a_16.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_17
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_17portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_17.clk0_core_clock_enable = "none",
		ram_block1a_17.clk0_input_clock_enable = "none",
		ram_block1a_17.connectivity_checking = "OFF",
		ram_block1a_17.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_17.init_file_layout = "port_a",
		ram_block1a_17.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_17.mem_init0 = 1024'h000000000000000000000000000000000000000000000000000000000000339E3C1E0F81F81FC07F01FE03FE01FE00FF803FE00000000000000000000000000000000000000000000000000000000000000000000000000000000000000063870783E07C0FE07F01FE03FC07F807FC03FC000000000000000000000000000000,
		ram_block1a_17.operation_mode = "rom",
		ram_block1a_17.port_a_address_clear = "none",
		ram_block1a_17.port_a_address_width = 10,
		ram_block1a_17.port_a_data_out_clear = "none",
		ram_block1a_17.port_a_data_out_clock = "none",
		ram_block1a_17.port_a_data_width = 1,
		ram_block1a_17.port_a_first_address = 0,
		ram_block1a_17.port_a_first_bit_number = 17,
		ram_block1a_17.port_a_last_address = 1023,
		ram_block1a_17.port_a_logical_ram_depth = 1024,
		ram_block1a_17.port_a_logical_ram_width = 36,
		ram_block1a_17.ram_block_type = "AUTO",
		ram_block1a_17.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_18
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_18portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_18.clk0_core_clock_enable = "none",
		ram_block1a_18.clk0_input_clock_enable = "none",
		ram_block1a_18.connectivity_checking = "OFF",
		ram_block1a_18.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_18.init_file_layout = "port_a",
		ram_block1a_18.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_18.mem_init0 = 1024'h000000000000000000000000000000000000000000000000000000000000707E03FE007FF8003FFF0001FFFE0001FFFF80001FFFFFE0000000000000000000000000000000000000000000000000000000000000000000000000000000001F80FF801FFC001FFF0001FFFC0007FFFC0003FFFFFFFFE000000000000000000000,
		ram_block1a_18.operation_mode = "rom",
		ram_block1a_18.port_a_address_clear = "none",
		ram_block1a_18.port_a_address_width = 10,
		ram_block1a_18.port_a_data_out_clear = "none",
		ram_block1a_18.port_a_data_out_clock = "none",
		ram_block1a_18.port_a_data_width = 1,
		ram_block1a_18.port_a_first_address = 0,
		ram_block1a_18.port_a_first_bit_number = 18,
		ram_block1a_18.port_a_last_address = 1023,
		ram_block1a_18.port_a_logical_ram_depth = 1024,
		ram_block1a_18.port_a_logical_ram_width = 36,
		ram_block1a_18.ram_block_type = "AUTO",
		ram_block1a_18.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_19
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_19portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_19.clk0_core_clock_enable = "none",
		ram_block1a_19.clk0_input_clock_enable = "none",
		ram_block1a_19.connectivity_checking = "OFF",
		ram_block1a_19.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_19.init_file_layout = "port_a",
		ram_block1a_19.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_19.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000FFE0001FFFFF8000000FFFFFFFE000000007FFFFFFFFFE0000000000000000000000000000000000000000000000000000000000000000000000000000000007F80007FFFFC000000FFFFFFFC00000003FFFFFFFFFFFFE000000000000000000000,
		ram_block1a_19.operation_mode = "rom",
		ram_block1a_19.port_a_address_clear = "none",
		ram_block1a_19.port_a_address_width = 10,
		ram_block1a_19.port_a_data_out_clear = "none",
		ram_block1a_19.port_a_data_out_clock = "none",
		ram_block1a_19.port_a_data_width = 1,
		ram_block1a_19.port_a_first_address = 0,
		ram_block1a_19.port_a_first_bit_number = 19,
		ram_block1a_19.port_a_last_address = 1023,
		ram_block1a_19.port_a_logical_ram_depth = 1024,
		ram_block1a_19.port_a_logical_ram_width = 36,
		ram_block1a_19.ram_block_type = "AUTO",
		ram_block1a_19.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_20
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_20portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_20.clk0_core_clock_enable = "none",
		ram_block1a_20.clk0_input_clock_enable = "none",
		ram_block1a_20.connectivity_checking = "OFF",
		ram_block1a_20.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_20.init_file_layout = "port_a",
		ram_block1a_20.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_20.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000001FFFFFFFFF800000000000001FFFFFFFFFFFFFFFFFFE000000000000000000000000000000000000000000000000000000000000000000000000000000000007FFFFFFFFC00000000000003FFFFFFFFFFFFFFFFFFFFE000000000000000000000,
		ram_block1a_20.operation_mode = "rom",
		ram_block1a_20.port_a_address_clear = "none",
		ram_block1a_20.port_a_address_width = 10,
		ram_block1a_20.port_a_data_out_clear = "none",
		ram_block1a_20.port_a_data_out_clock = "none",
		ram_block1a_20.port_a_data_width = 1,
		ram_block1a_20.port_a_first_address = 0,
		ram_block1a_20.port_a_first_bit_number = 20,
		ram_block1a_20.port_a_last_address = 1023,
		ram_block1a_20.port_a_logical_ram_depth = 1024,
		ram_block1a_20.port_a_logical_ram_width = 36,
		ram_block1a_20.ram_block_type = "AUTO",
		ram_block1a_20.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_21
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_21portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_21.clk0_core_clock_enable = "none",
		ram_block1a_21.clk0_input_clock_enable = "none",
		ram_block1a_21.connectivity_checking = "OFF",
		ram_block1a_21.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_21.init_file_layout = "port_a",
		ram_block1a_21.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_21.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000007FFFFFFFFFFFF80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007FFFFFFFFFFC00000000000000000000000000000000000000000000000000000000,
		ram_block1a_21.operation_mode = "rom",
		ram_block1a_21.port_a_address_clear = "none",
		ram_block1a_21.port_a_address_width = 10,
		ram_block1a_21.port_a_data_out_clear = "none",
		ram_block1a_21.port_a_data_out_clock = "none",
		ram_block1a_21.port_a_data_width = 1,
		ram_block1a_21.port_a_first_address = 0,
		ram_block1a_21.port_a_first_bit_number = 21,
		ram_block1a_21.port_a_last_address = 1023,
		ram_block1a_21.port_a_logical_ram_depth = 1024,
		ram_block1a_21.port_a_logical_ram_width = 36,
		ram_block1a_21.ram_block_type = "AUTO",
		ram_block1a_21.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_22
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_22portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_22.clk0_core_clock_enable = "none",
		ram_block1a_22.clk0_input_clock_enable = "none",
		ram_block1a_22.connectivity_checking = "OFF",
		ram_block1a_22.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_22.init_file_layout = "port_a",
		ram_block1a_22.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_22.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000007FFFFFFFFFFFF80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007FFFFFFFFFFC00000000000000000000000000000000000000000000000000000000,
		ram_block1a_22.operation_mode = "rom",
		ram_block1a_22.port_a_address_clear = "none",
		ram_block1a_22.port_a_address_width = 10,
		ram_block1a_22.port_a_data_out_clear = "none",
		ram_block1a_22.port_a_data_out_clock = "none",
		ram_block1a_22.port_a_data_width = 1,
		ram_block1a_22.port_a_first_address = 0,
		ram_block1a_22.port_a_first_bit_number = 22,
		ram_block1a_22.port_a_last_address = 1023,
		ram_block1a_22.port_a_logical_ram_depth = 1024,
		ram_block1a_22.port_a_logical_ram_width = 36,
		ram_block1a_22.ram_block_type = "AUTO",
		ram_block1a_22.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_23
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_23portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_23.clk0_core_clock_enable = "none",
		ram_block1a_23.clk0_input_clock_enable = "none",
		ram_block1a_23.connectivity_checking = "OFF",
		ram_block1a_23.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_23.init_file_layout = "port_a",
		ram_block1a_23.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_23.mem_init0 = 1024'h00000000000000000000000000000000000000000000000000000000000000000000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE000000000000000000000,
		ram_block1a_23.operation_mode = "rom",
		ram_block1a_23.port_a_address_clear = "none",
		ram_block1a_23.port_a_address_width = 10,
		ram_block1a_23.port_a_data_out_clear = "none",
		ram_block1a_23.port_a_data_out_clock = "none",
		ram_block1a_23.port_a_data_width = 1,
		ram_block1a_23.port_a_first_address = 0,
		ram_block1a_23.port_a_first_bit_number = 23,
		ram_block1a_23.port_a_last_address = 1023,
		ram_block1a_23.port_a_logical_ram_depth = 1024,
		ram_block1a_23.port_a_logical_ram_width = 36,
		ram_block1a_23.ram_block_type = "AUTO",
		ram_block1a_23.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_24
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_24portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_24.clk0_core_clock_enable = "none",
		ram_block1a_24.clk0_input_clock_enable = "none",
		ram_block1a_24.connectivity_checking = "OFF",
		ram_block1a_24.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_24.init_file_layout = "port_a",
		ram_block1a_24.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_24.mem_init0 = 1024'h00000000000000000000000000000000000000000000000000000000000037C40CAA9B9C1FF001FFFFE007FF071CCC96AA5B3C0392A0000000000000000000000000000000000000000000000000000000000000000000000000000000005A7C94B31E0001F83E1E1E0FE00003E39B6AA9380654FD4000000000000000000000,
		ram_block1a_24.operation_mode = "rom",
		ram_block1a_24.port_a_address_clear = "none",
		ram_block1a_24.port_a_address_width = 10,
		ram_block1a_24.port_a_data_out_clear = "none",
		ram_block1a_24.port_a_data_out_clock = "none",
		ram_block1a_24.port_a_data_width = 1,
		ram_block1a_24.port_a_first_address = 0,
		ram_block1a_24.port_a_first_bit_number = 24,
		ram_block1a_24.port_a_last_address = 1023,
		ram_block1a_24.port_a_logical_ram_depth = 1024,
		ram_block1a_24.port_a_logical_ram_width = 36,
		ram_block1a_24.ram_block_type = "AUTO",
		ram_block1a_24.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_25
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_25portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_25.clk0_core_clock_enable = "none",
		ram_block1a_25.clk0_input_clock_enable = "none",
		ram_block1a_25.connectivity_checking = "OFF",
		ram_block1a_25.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_25.init_file_layout = "port_a",
		ram_block1a_25.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_25.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000007C095A66787C000FFE0000000000FF03C38E66C96AAADB20000000000000000000000000000000000000000000000000000000000000000000000000000000002355B38F01FFFE003FE01FF00000001F87199B6AAB67032000000000000000000000,
		ram_block1a_25.operation_mode = "rom",
		ram_block1a_25.port_a_address_clear = "none",
		ram_block1a_25.port_a_address_width = 10,
		ram_block1a_25.port_a_data_out_clear = "none",
		ram_block1a_25.port_a_data_out_clock = "none",
		ram_block1a_25.port_a_data_width = 1,
		ram_block1a_25.port_a_first_address = 0,
		ram_block1a_25.port_a_first_bit_number = 25,
		ram_block1a_25.port_a_last_address = 1023,
		ram_block1a_25.port_a_logical_ram_depth = 1024,
		ram_block1a_25.port_a_logical_ram_width = 36,
		ram_block1a_25.ram_block_type = "AUTO",
		ram_block1a_25.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_26
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_26portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_26.clk0_core_clock_enable = "none",
		ram_block1a_26.clk0_input_clock_enable = "none",
		ram_block1a_26.connectivity_checking = "OFF",
		ram_block1a_26.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_26.init_file_layout = "port_a",
		ram_block1a_26.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_26.mem_init0 = 1024'h00000000000000000000000000000000000000000000000000000000000053F1934B52A9555555555555555555AA952B4B6DB3331C20000000000000000000000000000000000000000000000000000000000000000000000000000000000399252A555555556AAAB555555555552A52D24CCC7800E000000000000000000000,
		ram_block1a_26.operation_mode = "rom",
		ram_block1a_26.port_a_address_clear = "none",
		ram_block1a_26.port_a_address_width = 10,
		ram_block1a_26.port_a_data_out_clear = "none",
		ram_block1a_26.port_a_data_out_clock = "none",
		ram_block1a_26.port_a_data_width = 1,
		ram_block1a_26.port_a_first_address = 0,
		ram_block1a_26.port_a_first_bit_number = 26,
		ram_block1a_26.port_a_last_address = 1023,
		ram_block1a_26.port_a_logical_ram_depth = 1024,
		ram_block1a_26.port_a_logical_ram_width = 36,
		ram_block1a_26.ram_block_type = "AUTO",
		ram_block1a_26.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_27
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_27portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_27.clk0_core_clock_enable = "none",
		ram_block1a_27.clk0_input_clock_enable = "none",
		ram_block1a_27.connectivity_checking = "OFF",
		ram_block1a_27.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_27.init_file_layout = "port_a",
		ram_block1a_27.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_27.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000006554B6D93664CCCCCCCCCCCCCCCCCC99B366D9249696B5600000000000000000000000000000000000000000000000000000000000000000000000000000000056B49366CCCCCCCCE66673333333333366C9B6DA5AD5554000000000000000000000,
		ram_block1a_27.operation_mode = "rom",
		ram_block1a_27.port_a_address_clear = "none",
		ram_block1a_27.port_a_address_width = 10,
		ram_block1a_27.port_a_data_out_clear = "none",
		ram_block1a_27.port_a_data_out_clock = "none",
		ram_block1a_27.port_a_data_width = 1,
		ram_block1a_27.port_a_first_address = 0,
		ram_block1a_27.port_a_first_bit_number = 27,
		ram_block1a_27.port_a_last_address = 1023,
		ram_block1a_27.port_a_logical_ram_depth = 1024,
		ram_block1a_27.port_a_logical_ram_width = 36,
		ram_block1a_27.ram_block_type = "AUTO",
		ram_block1a_27.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_28
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_28portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_28.clk0_core_clock_enable = "none",
		ram_block1a_28.clk0_input_clock_enable = "none",
		ram_block1a_28.connectivity_checking = "OFF",
		ram_block1a_28.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_28.init_file_layout = "port_a",
		ram_block1a_28.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_28.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000002CCC71C70E1C3C3C3C3C3C3C3C3C3C7870E1C71C718E7300000000000000000000000000000000000000000000000000000000000000000000000000000000004E738F1E3C3C3C3C1E1E0F0F0F0F0F0F1E3871C639CCCCC000000000000000000000,
		ram_block1a_28.operation_mode = "rom",
		ram_block1a_28.port_a_address_clear = "none",
		ram_block1a_28.port_a_address_width = 10,
		ram_block1a_28.port_a_data_out_clear = "none",
		ram_block1a_28.port_a_data_out_clock = "none",
		ram_block1a_28.port_a_data_width = 1,
		ram_block1a_28.port_a_first_address = 0,
		ram_block1a_28.port_a_first_bit_number = 28,
		ram_block1a_28.port_a_last_address = 1023,
		ram_block1a_28.port_a_logical_ram_depth = 1024,
		ram_block1a_28.port_a_logical_ram_width = 36,
		ram_block1a_28.ram_block_type = "AUTO",
		ram_block1a_28.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_29
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_29portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_29.clk0_core_clock_enable = "none",
		ram_block1a_29.clk0_input_clock_enable = "none",
		ram_block1a_29.connectivity_checking = "OFF",
		ram_block1a_29.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_29.init_file_layout = "port_a",
		ram_block1a_29.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_29.mem_init0 = 1024'h00000000000000000000000000000000000000000000000000000000000063C3F03F01FC03FC03FC03FC03FC03F80FE03F03F07E0F000000000000000000000000000000000000000000000000000000000000000000000000000000000041F07F01FC03FC03FE01FF00FF00FF00FE07F03E07C3C3C000000000000000000000,
		ram_block1a_29.operation_mode = "rom",
		ram_block1a_29.port_a_address_clear = "none",
		ram_block1a_29.port_a_address_width = 10,
		ram_block1a_29.port_a_data_out_clear = "none",
		ram_block1a_29.port_a_data_out_clock = "none",
		ram_block1a_29.port_a_data_width = 1,
		ram_block1a_29.port_a_first_address = 0,
		ram_block1a_29.port_a_first_bit_number = 29,
		ram_block1a_29.port_a_last_address = 1023,
		ram_block1a_29.port_a_logical_ram_depth = 1024,
		ram_block1a_29.port_a_logical_ram_width = 36,
		ram_block1a_29.ram_block_type = "AUTO",
		ram_block1a_29.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_30
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_30portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_30.clk0_core_clock_enable = "none",
		ram_block1a_30.clk0_input_clock_enable = "none",
		ram_block1a_30.connectivity_checking = "OFF",
		ram_block1a_30.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_30.init_file_layout = "port_a",
		ram_block1a_30.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_30.mem_init0 = 1024'h000000000000000000000000000000000000000000000000000000000000603FF000FFFC0003FFFC0003FFFC0007FFE000FFF001FF0000000000000000000000000000000000000000000000000000000000000000000000000000000000400FFF0003FFFC0001FFFF0000FFFF0001FFF001FFC03FC000000000000000000000,
		ram_block1a_30.operation_mode = "rom",
		ram_block1a_30.port_a_address_clear = "none",
		ram_block1a_30.port_a_address_width = 10,
		ram_block1a_30.port_a_data_out_clear = "none",
		ram_block1a_30.port_a_data_out_clock = "none",
		ram_block1a_30.port_a_data_width = 1,
		ram_block1a_30.port_a_first_address = 0,
		ram_block1a_30.port_a_first_bit_number = 30,
		ram_block1a_30.port_a_last_address = 1023,
		ram_block1a_30.port_a_logical_ram_depth = 1024,
		ram_block1a_30.port_a_logical_ram_width = 36,
		ram_block1a_30.ram_block_type = "AUTO",
		ram_block1a_30.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_31
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_31portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_31.clk0_core_clock_enable = "none",
		ram_block1a_31.clk0_input_clock_enable = "none",
		ram_block1a_31.connectivity_checking = "OFF",
		ram_block1a_31.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_31.init_file_layout = "port_a",
		ram_block1a_31.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_31.mem_init0 = 1024'h00000000000000000000000000000000000000000000000000000000000060000FFFFFFC00000003FFFFFFFC0000001FFFFFF00000E000000000000000000000000000000000000000000000000000000000000000000000000000000000400000FFFFFFFC00000000FFFFFFFF0000000FFFFFC0002000000000000000000000,
		ram_block1a_31.operation_mode = "rom",
		ram_block1a_31.port_a_address_clear = "none",
		ram_block1a_31.port_a_address_width = 10,
		ram_block1a_31.port_a_data_out_clear = "none",
		ram_block1a_31.port_a_data_out_clock = "none",
		ram_block1a_31.port_a_data_width = 1,
		ram_block1a_31.port_a_first_address = 0,
		ram_block1a_31.port_a_first_bit_number = 31,
		ram_block1a_31.port_a_last_address = 1023,
		ram_block1a_31.port_a_logical_ram_depth = 1024,
		ram_block1a_31.port_a_logical_ram_width = 36,
		ram_block1a_31.ram_block_type = "AUTO",
		ram_block1a_31.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_32
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_32portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_32.clk0_core_clock_enable = "none",
		ram_block1a_32.clk0_input_clock_enable = "none",
		ram_block1a_32.connectivity_checking = "OFF",
		ram_block1a_32.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_32.init_file_layout = "port_a",
		ram_block1a_32.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_32.mem_init0 = 1024'h000000000000000000000000000000000000000000000000000000000000600000000003FFFFFFFFFFFFFFFC0000000000000FFFFFE00000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000003FFFFFFFFFFFFFFFF0000000000003FFFE000000000000000000000,
		ram_block1a_32.operation_mode = "rom",
		ram_block1a_32.port_a_address_clear = "none",
		ram_block1a_32.port_a_address_width = 10,
		ram_block1a_32.port_a_data_out_clear = "none",
		ram_block1a_32.port_a_data_out_clock = "none",
		ram_block1a_32.port_a_data_width = 1,
		ram_block1a_32.port_a_first_address = 0,
		ram_block1a_32.port_a_first_bit_number = 32,
		ram_block1a_32.port_a_last_address = 1023,
		ram_block1a_32.port_a_logical_ram_depth = 1024,
		ram_block1a_32.port_a_logical_ram_width = 36,
		ram_block1a_32.ram_block_type = "AUTO",
		ram_block1a_32.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_33
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_33portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_33.clk0_core_clock_enable = "none",
		ram_block1a_33.clk0_input_clock_enable = "none",
		ram_block1a_33.connectivity_checking = "OFF",
		ram_block1a_33.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_33.init_file_layout = "port_a",
		ram_block1a_33.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_33.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000006000000000000000000000000003FFFFFFFFFFFFFFFFFFE000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000FFFFFFFFFFFFFFFFE000000000000000000000,
		ram_block1a_33.operation_mode = "rom",
		ram_block1a_33.port_a_address_clear = "none",
		ram_block1a_33.port_a_address_width = 10,
		ram_block1a_33.port_a_data_out_clear = "none",
		ram_block1a_33.port_a_data_out_clock = "none",
		ram_block1a_33.port_a_data_width = 1,
		ram_block1a_33.port_a_first_address = 0,
		ram_block1a_33.port_a_first_bit_number = 33,
		ram_block1a_33.port_a_last_address = 1023,
		ram_block1a_33.port_a_logical_ram_depth = 1024,
		ram_block1a_33.port_a_logical_ram_width = 36,
		ram_block1a_33.ram_block_type = "AUTO",
		ram_block1a_33.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_34
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_34portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_34.clk0_core_clock_enable = "none",
		ram_block1a_34.clk0_input_clock_enable = "none",
		ram_block1a_34.connectivity_checking = "OFF",
		ram_block1a_34.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_34.init_file_layout = "port_a",
		ram_block1a_34.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_34.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE0000000000000000000000000000000000000000000000000000000000000000000000000000000003FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE000000000000000000000,
		ram_block1a_34.operation_mode = "rom",
		ram_block1a_34.port_a_address_clear = "none",
		ram_block1a_34.port_a_address_width = 10,
		ram_block1a_34.port_a_data_out_clear = "none",
		ram_block1a_34.port_a_data_out_clock = "none",
		ram_block1a_34.port_a_data_width = 1,
		ram_block1a_34.port_a_first_address = 0,
		ram_block1a_34.port_a_first_bit_number = 34,
		ram_block1a_34.port_a_last_address = 1023,
		ram_block1a_34.port_a_logical_ram_depth = 1024,
		ram_block1a_34.port_a_logical_ram_width = 36,
		ram_block1a_34.ram_block_type = "AUTO",
		ram_block1a_34.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_35
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_35portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_35.clk0_core_clock_enable = "none",
		ram_block1a_35.clk0_input_clock_enable = "none",
		ram_block1a_35.connectivity_checking = "OFF",
		ram_block1a_35.init_file = "../../ip/Robot_Rom/arm_rom.mif",
		ram_block1a_35.init_file_layout = "port_a",
		ram_block1a_35.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_35.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_35.operation_mode = "rom",
		ram_block1a_35.port_a_address_clear = "none",
		ram_block1a_35.port_a_address_width = 10,
		ram_block1a_35.port_a_data_out_clear = "none",
		ram_block1a_35.port_a_data_out_clock = "none",
		ram_block1a_35.port_a_data_width = 1,
		ram_block1a_35.port_a_first_address = 0,
		ram_block1a_35.port_a_first_bit_number = 35,
		ram_block1a_35.port_a_last_address = 1023,
		ram_block1a_35.port_a_logical_ram_depth = 1024,
		ram_block1a_35.port_a_logical_ram_width = 36,
		ram_block1a_35.ram_block_type = "AUTO",
		ram_block1a_35.lpm_type = "cycloneive_ram_block";
	assign
		address_a_wire = address_a,
		q_a = {wire_ram_block1a_35portadataout[0], wire_ram_block1a_34portadataout[0], wire_ram_block1a_33portadataout[0], wire_ram_block1a_32portadataout[0], wire_ram_block1a_31portadataout[0], wire_ram_block1a_30portadataout[0], wire_ram_block1a_29portadataout[0], wire_ram_block1a_28portadataout[0], wire_ram_block1a_27portadataout[0], wire_ram_block1a_26portadataout[0], wire_ram_block1a_25portadataout[0], wire_ram_block1a_24portadataout[0], wire_ram_block1a_23portadataout[0], wire_ram_block1a_22portadataout[0], wire_ram_block1a_21portadataout[0], wire_ram_block1a_20portadataout[0], wire_ram_block1a_19portadataout[0], wire_ram_block1a_18portadataout[0], wire_ram_block1a_17portadataout[0], wire_ram_block1a_16portadataout[0], wire_ram_block1a_15portadataout[0], wire_ram_block1a_14portadataout[0], wire_ram_block1a_13portadataout[0], wire_ram_block1a_12portadataout[0], wire_ram_block1a_11portadataout[0], wire_ram_block1a_10portadataout[0], wire_ram_block1a_9portadataout[0], wire_ram_block1a_8portadataout[0], wire_ram_block1a_7portadataout[0], wire_ram_block1a_6portadataout[0], wire_ram_block1a_5portadataout[0], wire_ram_block1a_4portadataout[0], wire_ram_block1a_3portadataout[0], wire_ram_block1a_2portadataout[0], wire_ram_block1a_1portadataout[0], wire_ram_block1a_0portadataout[0]};
endmodule //Robot_Rom_altsyncram
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module Robot_Rom (
	address,
	clock,
	q)/* synthesis synthesis_clearbox = 1 */;

	input	[9:0]  address;
	input	  clock;
	output	[35:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1	  clock;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire [35:0] sub_wire0;
	wire [35:0] q = sub_wire0[35:0];

	Robot_Rom_altsyncram	Robot_Rom_altsyncram_component (
				.address_a (address),
				.clock0 (clock),
				.q_a (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ADDRESSSTALL_A NUMERIC "0"
// Retrieval info: PRIVATE: AclrAddr NUMERIC "0"
// Retrieval info: PRIVATE: AclrByte NUMERIC "0"
// Retrieval info: PRIVATE: AclrOutput NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_ENABLE NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_SIZE NUMERIC "9"
// Retrieval info: PRIVATE: BlankMemory NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_INPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_OUTPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: Clken NUMERIC "0"
// Retrieval info: PRIVATE: IMPLEMENT_IN_LES NUMERIC "0"
// Retrieval info: PRIVATE: INIT_FILE_LAYOUT STRING "PORT_A"
// Retrieval info: PRIVATE: INIT_TO_SIM_X NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone IV E"
// Retrieval info: PRIVATE: JTAG_ENABLED NUMERIC "0"
// Retrieval info: PRIVATE: JTAG_ID STRING "NONE"
// Retrieval info: PRIVATE: MAXIMUM_DEPTH NUMERIC "0"
// Retrieval info: PRIVATE: MIFfilename STRING "../../ip/Robot_Rom/arm_rom.mif"
// Retrieval info: PRIVATE: NUMWORDS_A NUMERIC "1024"
// Retrieval info: PRIVATE: RAM_BLOCK_TYPE NUMERIC "0"
// Retrieval info: PRIVATE: RegAddr NUMERIC "1"
// Retrieval info: PRIVATE: RegOutput NUMERIC "0"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: SingleClock NUMERIC "1"
// Retrieval info: PRIVATE: UseDQRAM NUMERIC "0"
// Retrieval info: PRIVATE: WidthAddr NUMERIC "10"
// Retrieval info: PRIVATE: WidthData NUMERIC "36"
// Retrieval info: PRIVATE: rden NUMERIC "0"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: ADDRESS_ACLR_A STRING "NONE"
// Retrieval info: CONSTANT: CLOCK_ENABLE_INPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: CLOCK_ENABLE_OUTPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: INIT_FILE STRING "../../ip/Robot_Rom/arm_rom.mif"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone IV E"
// Retrieval info: CONSTANT: LPM_HINT STRING "ENABLE_RUNTIME_MOD=NO"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altsyncram"
// Retrieval info: CONSTANT: NUMWORDS_A NUMERIC "1024"
// Retrieval info: CONSTANT: OPERATION_MODE STRING "ROM"
// Retrieval info: CONSTANT: OUTDATA_ACLR_A STRING "NONE"
// Retrieval info: CONSTANT: OUTDATA_REG_A STRING "UNREGISTERED"
// Retrieval info: CONSTANT: WIDTHAD_A NUMERIC "10"
// Retrieval info: CONSTANT: WIDTH_A NUMERIC "36"
// Retrieval info: CONSTANT: WIDTH_BYTEENA_A NUMERIC "1"
// Retrieval info: USED_PORT: address 0 0 10 0 INPUT NODEFVAL "address[9..0]"
// Retrieval info: USED_PORT: clock 0 0 0 0 INPUT VCC "clock"
// Retrieval info: USED_PORT: q 0 0 36 0 OUTPUT NODEFVAL "q[35..0]"
// Retrieval info: CONNECT: @address_a 0 0 10 0 address 0 0 10 0
// Retrieval info: CONNECT: @clock0 0 0 0 0 clock 0 0 0 0
// Retrieval info: CONNECT: q 0 0 36 0 @q_a 0 0 36 0
// Retrieval info: GEN_FILE: TYPE_NORMAL Robot_Rom.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL Robot_Rom.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL Robot_Rom.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL Robot_Rom.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL Robot_Rom_inst.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL Robot_Rom_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL Robot_Rom_syn.v TRUE
// Retrieval info: LIB_FILE: altera_mf
